/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    CollectionDialog: typeof import('./src/components/CollectionDialog.vue')['default']
    OrdersTable: typeof import('./src/components/OrdersTable.vue')['default']
    OrderStatusBadge: typeof import('./src/components/OrderStatusBadge.vue')['default']
    ProductDialog: typeof import('./src/components/ProductDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeGrid: typeof import('./src/components/ThemeGrid.vue')['default']
  }
}
